#!/bin/sh
/bin/mount -n -o remount,rw /

/bin/mount -a
echo Starting Network
modprobe i2c-core
modprobe i2c-algo-bit
modprobe i2c-omap1510
modprobe soundcore
modprobe omap-audio
modprobe omap1510-aic23

#/sbin/ifconfig lo 127.0.0.1 netmask 255.0.0.0 broadcast 127.255.255.255
#/sbin/route add -net 127.0.0.0 netmask 255.0.0.0 lo
#/sbin/ifconfig eth0 10.1.3.3 netmask 255.255.0.0 broadcast 10.1.255.255
#/sbin/route add default gw 10.1.0.100 eth0
